project_name: darvaza_kube
builds:
  - main: ./cmd/darvaza-kube-ccm
    id: darvaza-kube-ccm
    binary: darvaza-kube-ccm
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X darvaza.org/kube/pkg/version.Version={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}
      - -X darvaza.org/kube/pkg/version.Branch={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}
      - -X darvaza.org/kube/pkg/version.Commit={{ .ShortCommit }}
      - -X darvaza.org/kube/pkg/version.BuildDate={{ .Timestamp }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    env:
      - CGO_ENABLED=0

archives:
  - id: darvaza-kube
    builds:
      - darvaza-kube-ccm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.xz
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

kos:
  - id: container-ccm
    build: darvaza-kube-ccm
    main: ./cmd/darvaza-kube-ccm
    repository: "quay.io/darvaza/kube-ccm"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - '{{ .Tag }}'
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
