builds:
  - main: ./cmd/darvaza-kube-ccm
    id: darvaza-kube-ccm
    binary: darvaza-kube-ccm
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X darvaza.org/kube/pkg/version.Version={{ if .IsSnapshot }}{{ .Version }}{{ else }} {{ .Tag }}{{ end }}
      - -X darvaza.org/kube/pkg/version.Branch={{ if .IsSnapshot }}{{ .Version }}{{ else }} {{ .Tag }}{{ end }}
      - -X darvaza.org/kube/pkg/version.Commit={{ .ShortCommit }}
      - -X darvaza.org/kube/pkg/version.BuildDate={{ .Timestamp }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_ppc64le
      - darwin_amd64
      - darwin_arm64
    env:
      - CGO_ENABLED=0

# Checksum all binaries.
checksum:
  name_template: "checksums.txt"
