name: Build
on:
  push:
    branches-ignore:
      - '**-wip'
  pull_request:
    branches:
      - "*"
jobs:
  make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: make
    - name: Test
      run: make test
